---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactappdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
      name: reactapppod
    spec:
      containers:
      - image: devopswthaws58/react-app
        name: reactappcontainer
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: reactappsvc
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: reactapp
  type: LoadBalancer
