---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mavenwebapp
      name: mavenwebapppod
    spec:
      containers:
      - image: ashokit/mavenwebapp
        imagePullPolicy: Always
        name: mavenwebappcontainer
        resources:
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: mavenwebapp
  type: LoadBalancer
